#!/bin/bash

# Mount EFS disk
wget https://www.dropbox.com/s/uz909a9lpc5rk7h/monta_efs
chmod 755 monta-efs
sudo ./monta-efs fs-eadc9f93

# pip install MscProject/pix
# Install
# pip install MscProject/pix
# git clone --recursive https://github.com/NVIDIA/apex.git && cd apex && pip3 install . && cd .. && rm -rf apex
